/**
 * Generates a self-contained consulting-grade HTML health assessment.
 * McKinsey-style design: ghost-slide executive summary, animated radar chart,
 * evidence-based findings with "Why this matters" callouts, heatmap coverage
 * map, prioritized action plan with ROI estimate, and social share section.
 *
 * Accepts the AnalysisResult type from the consulting analysis engine.
 * @module consulting-report
 */

import type { AnalysisResult } from './consulting-types.js';
import { getConsultingStyles } from './consulting-styles.js';
import { renderScoreArc, renderRadarChart, renderCoverageMap } from './consulting-charts.js';
import {
  sectionLabel,
  renderExecSummary,
  renderFindingsGrouped,
  renderActionPlan,
  renderMethodology,
} from './consulting-sections.js';
import { renderShareSection } from './consulting-share.js';
import { escapeHtml } from './html-template.js';

/**
 * Default OG image: inline SVG data URI (self-contained, no external deps).
 * Shows "Ody Refine" branding with warm palette.
 */
const OG_IMAGE = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1200' height='630' fill='%23f6f1e8'%3E%3Crect width='1200' height='630'/%3E%3Ctext x='600' y='280' text-anchor='middle' font-family='Georgia,serif' font-size='72' font-weight='700' fill='%2317110c'%3EKnowledge Health Report%3C/text%3E%3Ctext x='600' y='370' text-anchor='middle' font-family='sans-serif' font-size='28' font-weight='600' fill='%23bf5226'%3EOdy Refine%3C/text%3E%3C/svg%3E`;

/** Render the cover/header section with subtitle. */
function renderCover(result: AnalysisResult): string {
  const date = new Date(result.metadata.analyzedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  const docCount = result.metadata.documentCount;
  const hasFindings = result.findings.length > 0;
  const subtitle = hasFindings
    ? 'An independent assessment of your documentation integrity'
    : 'An independent assessment of your documentation health';
  return `<header class="cover" role="banner">
  <div class="cover-brand"><span class="cover-dot" aria-hidden="true"></span> Ody Refine</div>
  <h1>Knowledge Health Assessment</h1>
  <p class="cover-sub">${escapeHtml(subtitle)}</p>
  <p class="cover-meta">${escapeHtml(date)} &middot; ${String(docCount)} documents analyzed</p>
</header>`;
}

/** Render the health score hero: animated arc gauge + animated radar chart. */
function renderScoreHero(result: AnalysisResult): string {
  const arc = renderScoreArc(result.healthScore.overall);
  const radar = renderRadarChart(result.healthScore);
  return `<div class="score-hero">${arc}${radar}</div>`;
}

/** Render the heatmap coverage map section. */
function renderCoverageSection(result: AnalysisResult): string {
  const map = renderCoverageMap(result.documentMap, result.findings);
  if (!map) return '';
  return `<section class="section">
  ${sectionLabel('Knowledge Coverage Map')}
  ${map}
</section>`;
}

/** Render the findings section. */
function renderFindingsSection(result: AnalysisResult): string {
  if (result.findings.length === 0) return '';
  return `<section class="section">
  ${sectionLabel('Findings')}
  ${renderFindingsGrouped(result.findings)}
</section>`;
}

/** Render the action plan section with ROI estimate. */
function renderActionSection(result: AnalysisResult): string {
  const actionable = result.findings.filter((f) => f.severity !== 'info');
  if (actionable.length === 0) return '';
  return `<section class="section">
  ${sectionLabel('Recommended Actions')}
  ${renderActionPlan(result.findings, result.healthScore.overall)}
</section>`;
}

/** Render the methodology section. */
function renderMethodologySection(result: AnalysisResult): string {
  return `<section class="section">
  ${sectionLabel('Methodology')}
  ${renderMethodology(result.metadata)}
</section>`;
}

/** Render the footer with timestamp and feedback link. */
function renderFooter(timestamp: string): string {
  return `<footer class="report-footer" role="contentinfo">
  <div class="footer-cta">Scan your own docs &rarr; <code>npx ody-refine ./docs/</code></div>
  <div class="footer-links">GitHub: <a href="//github.com/ufukkaraca/ody-platform" target="_blank" rel="noopener">github.com/ufukkaraca/ody-platform</a> &middot; <a href="//github.com/ufukkaraca/ody-platform/issues" target="_blank" rel="noopener">Feedback</a></div>
  <div class="footer-gen">Generated by <span class="footer-brand">Ody Refine</span> &middot; ${escapeHtml(timestamp)}</div>
</footer>`;
}

/** Render the empty state when no findings are found. */
function renderEmptyState(): string {
  return `<div class="methodology" style="text-align:center;padding:3rem 1.5rem">
  <div style="font-size:2.5rem;margin-bottom:0.5rem">&#10003;</div>
  <p><strong style="font-family:var(--font-serif);font-size:1.2rem;color:var(--color-success)">No issues found</strong></p>
  <p style="margin-top:0.5rem">Your knowledge base looks healthy. Run again after your next documentation update.</p>
</div>`;
}

/**
 * Generate a self-contained consulting-grade HTML health assessment.
 * Produces valid HTML with <!DOCTYPE html>. No external JS dependencies.
 * Includes CSS-only animations, responsive layout, and print styles.
 *
 * @param result - The structured analysis result from the consulting engine.
 * @returns Complete HTML string ready to write to a file.
 */
export function generateConsultingReport(result: AnalysisResult): string {
  const hasFindings = result.findings.length > 0;

  const body = hasFindings
    ? [
        renderExecSummarySection(result),
        renderCoverageSection(result),
        renderFindingsSection(result),
        renderActionSection(result),
        renderMethodologySection(result),
      ].filter(Boolean).join('\n')
    : renderEmptyState() + renderMethodologySection(result);

  const shareHtml = hasFindings ? renderShareSection(result) : '';

  const scoreDesc = result.healthScore.overall >= 80 ? 'Healthy' : 'Needs attention';
  const ogDesc = `Score: ${String(result.healthScore.overall)}/100 — ${String(result.findings.length)} issues found. ${scoreDesc}.`;
  const timestamp = new Date().toISOString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <meta property="og:title" content="Knowledge Health Assessment — Ody Refine">
  <meta property="og:description" content="${escapeHtml(ogDesc)}">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="Ody Refine">
  <meta property="og:image" content="${OG_IMAGE}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="Knowledge Health Assessment — Ody Refine">
  <meta name="twitter:description" content="${escapeHtml(ogDesc)}">
  <meta name="twitter:image" content="${OG_IMAGE}">
  <title>Knowledge Health Assessment &mdash; Ody Refine</title>
  <style>${getConsultingStyles()}</style>
</head>
<body>
${renderCover(result)}
${renderScoreHero(result)}
<main>
${body}
</main>
${shareHtml}
${renderFooter(timestamp)}
</body>
</html>`;
}

/** Wrap the executive summary in a section. */
function renderExecSummarySection(result: AnalysisResult): string {
  return `<section class="section">
  ${sectionLabel('Executive Summary')}
  ${renderExecSummary(result)}
</section>`;
}
