/**
 * HTML template fragments for the Ody Refine health report.
 * Self-contained — no external links or resources.
 * @module html-template
 */

import { getReportStyles } from './html-styles.js';

/** CSS styles for the health report. */
export function getReportCss(): string {
  return getReportStyles();
}

/** Escape HTML special characters. */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Convert basic markdown to inline HTML after HTML-escaping the input.
 * Handles: fenced code blocks, inline code, and **bold**.
 * Safe: HTML is escaped first, then harmless markdown patterns are promoted.
 */
export function renderMarkdownInline(text: string): string {
  // 1. Escape HTML special chars first (safe baseline)
  const escaped = escapeHtml(text);

  // 2. Strip fenced code blocks — replace with <code>content</code>
  const noBlocks = escaped.replace(
    /```[^\n`]*\n?([\s\S]*?)```/g,
    (_m, inner: string) => `<code>${inner.trim()}</code>`,
  );

  // 3. Inline code: `code`
  const withCode = noBlocks.replace(/`([^`]+)`/g, '<code>$1</code>');

  // 4. Bold: **text**
  const withBold = withCode.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');

  return withBold;
}

/** Render the report header HTML with Ody branding. */
export function renderHeader(): string {
  return `<div class="report-header">
  <div class="brand"><span class="brand-dot"></span> Ody Refine</div>
  <h1>Ody Refine Health Report</h1>
  <p class="subtitle">Knowledge base integrity analysis</p>
</div>`;
}

/** Render the health score as a prominent SVG ring. */
export function renderScore(score: number): string {
  const r = 54;
  const circ = 2 * Math.PI * r;
  const offset = circ - (score / 100) * circ;
  const color =
    score === 100
      ? '#2d8a54'
      : score >= 80
        ? '#bf5226'
        : score >= 50
          ? '#b8860b'
          : '#c03030';
  const trackColor = 'rgba(20, 15, 10, 0.06)';
  return `<div class="score-section"><div>
  <svg class="score-ring" width="140" height="140" viewBox="0 0 140 140">
    <circle cx="70" cy="70" r="${String(r)}" stroke="${trackColor}"
      stroke-width="10" fill="none"/>
    <circle cx="70" cy="70" r="${String(r)}" stroke="${color}"
      stroke-width="10" fill="none"
      stroke-dasharray="${circ.toFixed(2)}"
      stroke-dashoffset="${offset.toFixed(2)}"
      transform="rotate(-90 70 70)" stroke-linecap="round"/>
    <text x="70" y="66" text-anchor="middle"
      font-size="36" font-weight="800" fill="#17110c">${String(score)}</text>
    <text x="70" y="86" text-anchor="middle"
      font-size="11" font-weight="600" fill="#8a7e72"
      letter-spacing="0.08em">/ 100</text>
  </svg>
  <div class="score-label">Health Score</div>
</div></div>`;
}

/** Render summary bars for detection counts grouped by type. */
export function renderSummaryCards(
  counts: Record<string, number>,
): string {
  const entries = Object.entries(counts);
  if (entries.length === 0) return '';
  const max = Math.max(...entries.map(([, c]) => c));
  const rows = entries
    .sort((a, b) => b[1] - a[1])
    .map(([type, count]) => {
      const pct = max > 0 ? Math.round((count / max) * 100) : 0;
      return `  <div class="summary-row">
    <span class="summary-type">${type}</span>
    <div class="summary-bar-track">
      <div class="summary-bar-fill" style="width:${String(pct)}%"></div>
    </div>
    <span class="summary-count">${String(count)}</span>
  </div>`;
    })
    .join('\n');
  return `<div class="summary-section">
  <div class="summary-title">Issues by Type</div>
${rows}
</div>`;
}

/** Render the footer with Ody branding, product link, and timestamp. */
export function renderFooter(timestamp: string): string {
  return `<div class="footer">
  <div class="footer-cta">Scan your own docs &rarr; <code>npx ody-refine ./docs/</code></div>
  <div class="footer-links">GitHub: <a href="//github.com/ufukkaraca/ody-platform" target="_blank" rel="noopener">github.com/ufukkaraca/ody-platform</a></div>
  <div class="footer-gen">Generated by <span class="brand-mark">Ody Refine</span> &middot; ${timestamp}</div>
</div>`;
}
