/**
 * HTML template fragments for the Ody Refine consulting-grade health report.
 * Self-contained — no external links or resources.
 * @module html-template
 */

import { getReportStyles } from './html-styles.js';

/** CSS styles for the health report. */
export function getReportCss(): string {
  return getReportStyles();
}

/** Escape HTML special characters. */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Convert basic markdown to inline HTML after HTML-escaping the input.
 * Handles: fenced code blocks, inline code, and **bold**.
 */
export function renderMarkdownInline(text: string): string {
  const escaped = escapeHtml(text);
  const noBlocks = escaped.replace(
    /```[^\n`]*\n?([\s\S]*?)```/g,
    (_m, inner: string) => `<code>${inner.trim()}</code>`,
  );
  const withCode = noBlocks.replace(/`([^`]+)`/g, '<code>$1</code>');
  return withCode.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
}

/** Render the report cover header with professional Ody branding. */
export function renderHeader(
  stats?: { nodeCount: number; durationMs: number },
): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  const nodeText = stats ? ` &middot; ${String(stats.nodeCount)} documents analyzed` : '';
  return `<header class="report-cover">
  <div class="cover-brand"><span class="cover-brand-dot"></span> ODY REFINE</div>
  <h1>Knowledge Health Report</h1>
  <p class="cover-meta">${dateStr}${nodeText}</p>
</header>`;
}

/** Render the health score as a prominent SVG gauge. */
export function renderScore(score: number): string {
  const r = 58;
  const circ = 2 * Math.PI * r;
  const offset = circ - (score / 100) * circ;
  const color = score >= 80 ? '#10B981' : score >= 50 ? '#F59E0B' : '#EF4444';
  return `<div class="score-display">
  <svg width="160" height="160" viewBox="0 0 160 160">
    <circle cx="80" cy="80" r="${String(r)}" stroke="#E2E8F0" stroke-width="12" fill="none"/>
    <circle cx="80" cy="80" r="${String(r)}" stroke="${color}" stroke-width="12" fill="none"
      stroke-dasharray="${circ.toFixed(1)}" stroke-dashoffset="${offset.toFixed(1)}"
      transform="rotate(-90 80 80)" stroke-linecap="round"/>
    <text x="80" y="74" text-anchor="middle" font-size="42" font-weight="800"
      fill="#0F172A" font-family="-apple-system,BlinkMacSystemFont,sans-serif">${String(score)}</text>
    <text x="80" y="98" text-anchor="middle" font-size="11" font-weight="600"
      fill="#94A3B8" letter-spacing="0.12em"
      font-family="-apple-system,BlinkMacSystemFont,sans-serif">OUT OF 100</text>
  </svg>
</div>`;
}

/** Render summary bars for detection counts grouped by type. */
export function renderSummaryCards(counts: Record<string, number>): string {
  const entries = Object.entries(counts);
  if (entries.length === 0) return '';
  const max = Math.max(...entries.map(([, c]) => c));
  const rows = entries
    .sort((a, b) => b[1] - a[1])
    .map(([type, count]) => {
      const pct = max > 0 ? Math.round((count / max) * 100) : 0;
      return `  <div class="summary-row">
    <span class="summary-type">${type}</span>
    <div class="summary-bar-track">
      <div class="summary-bar-fill" style="width:${String(pct)}%"></div>
    </div>
    <span class="summary-count">${String(count)}</span>
  </div>`;
    })
    .join('\n');
  return `<div class="summary-section">
  <div class="summary-title">Issues by Category</div>
${rows}
</div>`;
}

/** Render the footer with Ody branding, feedback link, and timestamp. */
export function renderFooter(timestamp: string): string {
  return `<footer class="report-footer" role="contentinfo">
  <div class="footer-cta">Scan your own docs &rarr; <code>npx ody-refine ./docs/</code></div>
  <div class="footer-links">GitHub: <a href="//github.com/ufukkaraca/ody-platform" target="_blank" rel="noopener">github.com/ufukkaraca/ody-platform</a> &middot; <a href="//github.com/ufukkaraca/ody-platform/issues" target="_blank" rel="noopener">Feedback</a></div>
  <div class="footer-gen">Generated by <span class="footer-brand">Ody Refine</span> &middot; ${timestamp}</div>
</footer>`;
}
