version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "vitest"
          - "eslint*"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "vitest"
          - "eslint*"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
