/**
 * Python training script generators for GRPO (Group Relative Policy Optimization).
 * @module training/grpo-script-generator
 */

/** Generate the GRPO import/config body. */
export function generateGrpoBody(
  model: string, lr: number, epochs: number, batchSize: number, warmupSteps: number,
): string {
  return [
    'from transformers import AutoModelForCausalLM, AutoTokenizer',
    'from trl import GRPOTrainer, GRPOConfig',
    'from peft import LoraConfig, get_peft_model',
    '',
    `MODEL_NAME = "${model}"`,
    `LEARNING_RATE = ${lr}`,
    `NUM_EPOCHS = ${epochs}`,
    `BATCH_SIZE = ${batchSize}`,
    `WARMUP_STEPS = ${warmupSteps}`,
    'MAX_LENGTH = 1024',
    'GROUP_SIZE = 4',
    '',
  ].join('\n');
}

/** Generate the GRPO training call. */
export function generateGrpoTrainCall(): string {
  return [
    '',
    'dataset = load_dataset("json", data_files=dataset_path, split="train")',
    '',
    '# Validate dataset columns (GRPO needs prompt + reward columns)',
    'if "prompt" not in dataset.column_names:',
    '    raise ValueError("Dataset missing required column: prompt")',
    '',
    'tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)',
    'if tokenizer.pad_token is None:',
    '    tokenizer.pad_token = tokenizer.eos_token',
    '',
    'model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)',
    '',
    '# Apply LoRA for memory efficiency',
    'peft_config = LoraConfig(',
    '    r=16,',
    '    lora_alpha=32,',
    '    lora_dropout=0.05,',
    '    target_modules=["q_proj", "v_proj"],',
    '    task_type="CAUSAL_LM",',
    ')',
    'model = get_peft_model(model, peft_config)',
    '',
    '# Reward function: keyword overlap against expected answer',
    'def reward_fn(completions, **kwargs):',
    '    expected = kwargs.get("expected_answer", [""] * len(completions))',
    '    rewards = []',
    '    for comp, exp in zip(completions, expected):',
    '        text = comp[0]["content"] if isinstance(comp, list) else str(comp)',
    '        exp_words = set(exp.lower().split())',
    '        comp_words = set(text.lower().split())',
    '        overlap = len(exp_words & comp_words) / max(len(exp_words), 1)',
    '        rewards.append(overlap)',
    '    return rewards',
    '',
    'training_args = GRPOConfig(',
    '    output_dir=OUTPUT_DIR,',
    '    num_train_epochs=NUM_EPOCHS,',
    '    per_device_train_batch_size=BATCH_SIZE,',
    '    learning_rate=LEARNING_RATE,',
    '    warmup_steps=WARMUP_STEPS,',
    '    logging_steps=10,',
    '    save_strategy="epoch",',
    '    num_generations=GROUP_SIZE,',
    '    max_completion_length=MAX_LENGTH,',
    ')',
    '',
    'trainer = GRPOTrainer(',
    '    model=model,',
    '    processing_class=tokenizer,',
    '    args=training_args,',
    '    train_dataset=dataset,',
    '    reward_funcs=[reward_fn],',
    ')',
    '',
    'trainer.train()',
    'model.save_pretrained(OUTPUT_DIR)',
    'tokenizer.save_pretrained(OUTPUT_DIR)',
    '',
    '# Emit artifact metadata for model-loader',
    'import datetime',
    'meta = {"modelPath": OUTPUT_DIR, "baseModel": MODEL_NAME, "method": "grpo", "timestamp": datetime.datetime.now(datetime.UTC).isoformat().replace("+00:00", "Z")}',
    'Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)',
    'with open(str(Path(OUTPUT_DIR) / "artifact-meta.json"), "w") as f:',
    '    json.dump(meta, f, indent=2)',
    'print("GRPO training complete")',
    '',
  ].join('\n');
}
