/**
 * Python training script generators for SFT (Supervised Fine-Tuning).
 * @module training/sft-script-generator
 */

/** Generate the SFT import/config body. */
export function generateSftBody(
  model: string, lr: number, epochs: number, batchSize: number, warmupSteps: number,
): string {
  return [
    'from transformers import AutoModelForCausalLM, AutoTokenizer',
    'from trl import SFTTrainer, SFTConfig',
    'from peft import LoraConfig, get_peft_model',
    '',
    `MODEL_NAME = "${model}"`,
    `LEARNING_RATE = ${lr}`,
    `NUM_EPOCHS = ${epochs}`,
    `BATCH_SIZE = ${batchSize}`,
    `WARMUP_STEPS = ${warmupSteps}`,
    'MAX_SEQ_LENGTH = 1024',
    '',
  ].join('\n');
}

/** Generate the SFT training call. */
export function generateSftTrainCall(): string {
  return [
    '',
    'dataset = load_dataset("json", data_files=dataset_path, split="train")',
    '',
    '# Validate dataset columns',
    'required_columns = {"instruction", "response"}',
    'missing = required_columns - set(dataset.column_names)',
    'if missing:',
    '    raise ValueError(f"Dataset missing required columns: {missing}. Expected: {required_columns}")',
    '',
    '# Use model\'s native chat template for better knowledge injection',
    'def format_chat(x):',
    '    if hasattr(tokenizer, "apply_chat_template"):',
    '        messages = [{"role": "user", "content": x["instruction"]}, {"role": "assistant", "content": x["response"]}]',
    '        return {"text": tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)}',
    '    return {"text": f"<|im_start|>user\\n{x[\'instruction\']}<|im_end|>\\n<|im_start|>assistant\\n{x[\'response\']}<|im_end|>"}',
    'dataset = dataset.map(format_chat)',
    '',
    'tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)',
    'if tokenizer.pad_token is None:',
    '    tokenizer.pad_token = tokenizer.eos_token',
    '',
    'model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)',
    '',
    '# Apply LoRA for memory efficiency',
    'peft_config = LoraConfig(',
    '    r=16,',
    '    lora_alpha=32,',
    '    lora_dropout=0.05,',
    '    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],',
    '    task_type="CAUSAL_LM",',
    ')',
    '',
    'training_args = SFTConfig(',
    '    output_dir=OUTPUT_DIR,',
    '    num_train_epochs=NUM_EPOCHS,',
    '    per_device_train_batch_size=BATCH_SIZE,',
    '    learning_rate=LEARNING_RATE,',
    '    warmup_steps=WARMUP_STEPS,',
    '    logging_steps=10,',
    '    save_strategy="epoch",',
    '    max_length=MAX_SEQ_LENGTH,',
    '    gradient_checkpointing=False,',
    '    report_to="none",',
    ')',
    '',
    'trainer = SFTTrainer(',
    '    model=model,',
    '    processing_class=tokenizer,',
    '    args=training_args,',
    '    train_dataset=dataset,',
    '    peft_config=peft_config,',
    ')',
    '',
    'trainer.train()',
    'model.save_pretrained(OUTPUT_DIR)',
    'tokenizer.save_pretrained(OUTPUT_DIR)',
    '',
    '# Emit artifact metadata for model-loader',
    'import datetime',
    'meta = {"modelPath": OUTPUT_DIR, "baseModel": MODEL_NAME, "method": "sft", "timestamp": datetime.datetime.now(datetime.UTC).isoformat().replace("+00:00", "Z")}',
    'Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)',
    'with open(str(Path(OUTPUT_DIR) / "artifact-meta.json"), "w") as f:',
    '    json.dump(meta, f, indent=2)',
    'print("SFT training complete")',
    '',
  ].join('\n');
}
